INSERT INTO TEAMS(NAME,ABBREVIATION) VALUES ('CD Castellón','CAS');
INSERT INTO TEAMS(NAME,ABBREVIATION) VALUES ('CD Leganés','LEG');
INSERT INTO TEAMS(NAME,ABBREVIATION) VALUES ('Real Zaragoza','ZAR');
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID)VALUES ('Cristian', 'Alvarez', 'ARG', 3);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Jair Jr','Amador','POR',3);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Francho','Serrano','ESP',3);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Víctor','Mollejo','ESP',3);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Daniel','Jimenez','ESP',2);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Nyom','Romeo','FRN',2);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Gonzalo','Aguilar','ESP',2);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Manuel','Sanchez','ESP',1);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Salvador','Ruiz','ESP',1);
INSERT INTO PLAYERS(NAME,SURNAME,NATIONALITY,TEAM_ID) VALUES ('Gonzalo','Crettaz','ESP',1);

